### ISSUE TITLE
Add working README.md for Express API

### ISSUE THREAD

**Issue by akroon3r** [bcgov/CITZ-HybridWorkplace#19]
Please include steps to get the api working locally in a readme.md found at /app/server

**Comment by akroon3r** [comment]
we need a basic readme explaining how to get the api running on local (docker instructions).

we also need to talk about how we're going to document the endpoints of the api (ie// swagger) and where it's going to be available.

my current project makes the full api swagger spec available at http://localhost:3000/api for example.

if you haven't worked with swagger/openapi spec, here's the documentation for you: https://swagger.io/specification/

**Comment by CITZ-rwk** [comment]
approved
