### ISSUE TITLE
Edit Community -> Community not found

### ISSUE THREAD

**Issue by dbarkowsky** [bcgov/CITZ-HybridWorkplace#388]
**Describe the bug**
When editing a community, I receive the error notification "Community not found."

**To Reproduce**
1. Go to a community
2. Edit the community
3. Click Edit button after making changes

**Expected behavior**
Expected edits to be saved and returned to community

**Screenshots**
![image](https://user-images.githubusercontent.com/37922247/180095161-8e09222a-34ff-4267-8dcc-1c66ec6948b6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Additional context**

**Comment by BradyMitch** [comment]
Resolved
